# Generated by Django 5.1.1 on 2024-10-22 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_student2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='student',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='student',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student',
            name='profile_img',
        ),
        migrations.RemoveField(
            model_name='student',
            name='updated_at',
        ),
    ]
