# Generated by Django 5.1.1 on 2024-10-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_student_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student2',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student2',
            name='gender',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
