# Generated by Django 5.1.1 on 2024-10-22 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_student2_file_student2_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student2',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
