# Generated by Django 5.1.1 on 2024-10-22 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_student2_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student2',
            name='file',
        ),
        migrations.RemoveField(
            model_name='student2',
            name='gender',
        ),
    ]
