# Generated by Django 5.1.1 on 2024-10-22 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_student2_file_remove_student2_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student2',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files/'),
        ),
        migrations.AddField(
            model_name='student2',
            name='gender',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
