# Generated by Django 5.1.1 on 2024-10-24 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_student_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='mobile_number',
            field=models.CharField(max_length=20),
        ),
    ]
