# Generated by Django 5.1.1 on 2025-04-13 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_products_slug'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
