# Generated by Django 5.1.1 on 2025-04-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('price',)},
        ),
    ]
