# Generated by Django 5.1.1 on 2025-04-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_alter_book_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ('price',), 'verbose_name': 'Book', 'verbose_name_plural': 'Book'},
        ),
    ]
