# Generated by Django 5.1.1 on 2025-04-14 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_alter_book_options'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='brand',
            unique_together={('brand_name', 'country')},
        ),
    ]
