# Generated by Django 5.1.1 on 2025-04-14 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_student2_age_gte_18'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='student2',
            name='age_gte_18',
        ),
    ]
