# Generated by Django 5.1.1 on 2025-04-14 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_student2_age_gte_18'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeStudent',
            fields=[
            ],
            options={
                'proxy': True,
                'constraints': [models.CheckConstraint(condition=models.Q(('age__gte', 21)), name='age_gte_21')],
                'indexes': [],
            },
            bases=('home.student2',),
        ),
    ]
