# Generated by Django 5.1.1 on 2025-05-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='sky',
            new_name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=models.URLField(max_length=1000),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand'),
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
