# Generated by Django 5.1.1 on 2025-05-05 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_student_student_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_img', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumb_mini', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('thumb_small', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('thumb_medium', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
                ('thumb_large', models.ImageField(blank=True, null=True, upload_to='images/thumbnails')),
            ],
        ),
    ]
