# Generated by Django 5.1.6 on 2025-08-06 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_author_publisher_remove_book_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='publishers',
            new_name='publisher',
        ),
        migrations.AlterField(
            model_name='book',
            name='book_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_publisher', to='home.author'),
        ),
    ]
